### ISSUE TITLE
Improve link on failed jobs to filter view in monitor tab

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_conductor_monitor#6]
Link is currently: http://platform.dnanexus.com/projects/GVVkfG84jzXB21zQJFJZX7k3/monitor/

Would be better as: https://platform.dnanexus.com/projects/GVVkfG84jzXB21zQJFJZX7k3/monitor?state.values=failed

**Comment by jethror1** [comment]
should also add `panx` into this to redirect to latest UI

**Comment by Yu-jinKim** [comment]
Fixed in #13
